<a href="https://colab.research.google.com/github/DigdinLogistico/Api-Fatec-2-Semestre/blob/main/Separa%C3%A7%C3%A3o_Produto.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
from google.colab import drive
drive.mount('/content/drive')

caminho='/content/drive/My Drive/API 2026 - Cargas perigosas/'

Mounted at /content/drive

In [ ]:
df = pd.read_csv(caminho + "Dadostratados.csv")

In [ ]:
# Isolar a coluna "produto"
produtos = df['Produto']

# Contar a aparição de cada produto
contagem_produtos = produtos.value_counts()

# Listar os 10 produtos mais frequentes
print("Top 10 Produtos mais frequentes:")
display(contagem_produtos.head(10))

# To study a specific product, you can filter the DataFrame:
# For example, to see all entries for 'Aspartame':
# aspartame_df = df[df['Produto'] == 'Aspartame']
# display(aspartame_df.head())

# Or, to get unique products:
# unique_produtos = produtos.unique()
# print("\nNúmero de produtos únicos:", len(unique_produtos))

Top 10 Produtos mais frequentes:

Produto
Álcool etílico não desnaturado, com teor alcoólico em volume maior ou igual a 80%, anidro ou hidratado para fins carburantes    80446
Produtos químicos, n.e.                                                                                                         79269
Óleo diesel                                                                                                                     61693
Inseticidas para uso na agricultura                                                                                             48674
Herbicidas para uso na agricultura                                                                                              42988
Hidróxido de sódio (soda cáustica)                                                                                              39797
Fungicidas para uso na agricultura                                                                                              29072
Gás liqüefeito de petróleo (GLP)                                                                                                28918
Ácido sulfúrico                                                                                                                 26598
Tintas e vernizes não especificados para usos em geral                                                                          23915
Name: count, dtype: int64

In [ ]:
# Get all unique products
unique_produtos = produtos.unique()

print(f"Número total de produtos únicos: {len(unique_produtos)}")
print("Todos os produtos únicos:")
display(unique_produtos)

Número total de produtos únicos: 11737
Todos os produtos únicos:

array(['Aspartame',
       'Álcool etílico não desnaturado, com teor alcoólico em volume maior ou igual a 80%, anidro ou hidratado para fins carburantes',
       'Seringas, agulhas, catéteres, cânulas, lancetas e instrumentos semelhantes',
       ..., '1-metilfenantreno',
       'Desperdícios, resíduos ou sucatas da produção de laminados longos de aços',
       '9,10-dimetilantraceno'], dtype=object)

In [ ]:
# Convert the unique products array to a DataFrame
df_produtos_unicos = pd.DataFrame(unique_produtos, columns=['Produto_Unico'])

# Define the output path in Google Drive
output_path = caminho + 'produtos_unicos.csv'

# Export to CSV
df_produtos_unicos.to_csv(output_path, index=False)

print(f"Lista de produtos únicos exportada para: {output_path}")

Lista de produtos únicos exportada para: /content/drive/My Drive/API 2026 - Cargas perigosas/produtos_unicos.csv

### Filtrando com a lista de produtos perigosos

In [ ]:
# Carregar a lista de produtos perigosos tratados
df_produtos_perigosos = pd.read_csv(caminho + 'produtos_perigosos_tratados.csv')

# Extrair a lista de nomes de produtos da coluna 'Produto_Unico'
# Assumindo que a coluna com os nomes dos produtos se chama 'Produto_Unico'
# ou a primeira coluna se o nome for desconhecido.
# Ajuste 'Produto_Unico' se o nome da coluna for diferente no CSV.
if 'Produto_Unico' in df_produtos_perigosos.columns:
    lista_produtos_para_filtrar = df_produtos_perigosos['Produto_Unico'].unique()
elif len(df_produtos_perigosos.columns) > 0:
    # Se não encontrar 'Produto_Unico', tenta a primeira coluna
    lista_produtos_para_filtrar = df_produtos_perigosos.iloc[:, 0].unique()
else:
    lista_produtos_para_filtrar = []
    print("Não foi possível encontrar a coluna de produtos ('Produto_Unico' ou primeira coluna) no arquivo 'produtos_perigosos_tratados.csv'.")

print(f"Número de produtos na lista de filtragem (produtos perigosos): {len(lista_produtos_para_filtrar)}")

Número de produtos na lista de filtragem (produtos perigosos): 1985

In [ ]:
# Aplicar o filtro no DataFrame original (df)
df_filtered_perigosos = df[df['Produto'].isin(lista_produtos_para_filtrar)]

print(f"Número original de linhas: {len(df)}")
print(f"Número de linhas após o filtro de produtos perigosos: {len(df_filtered_perigosos)}")

display(df_filtered_perigosos.head())

Número original de linhas: 1333721
Número de linhas após o filtro de produtos perigosos: 774325

,CNPJ,Razão Social,Município,Ano,Produto,Quantidade Transportada,Unidade de Medida,Tipo de Transporte,Tipo de Armazenamento,Plano de Emergência,UF - origem,UF - destino,Situação Cadastral
1,97.471.676/0001-03,DISTRIBUIDORA DE COMBUSTÍVEIS SAARA LTDA.,CASCAVEL,2024,"Álcool etílico não desnaturado, com teor alcoó...","1.000.000,00",Litro,Rodoviário,Tanques,Sim,SAO PAULO,PARANA,Ativa
5,32.597.126/0001-81,NEXTLOG TRANSPORTES LTDA,GUARULHOS,2024,"Solventes e diluentes orgânicos compostos, n.e...","12,00",Galão,Rodoviário,Outros,Não,SAO PAULO,SAO PAULO,Ativa
6,04.898.593/0001-06,A. L. GUILHERME LTDA,SUMARE,2024,"Dióxido de carbono (gás carbônico, anidrido ca...","45.000,00",Metro Cúbico,Rodoviário,Outros,Não,SAO PAULO,SAO PAULO,Ativa
7,39.838.338/0001-52,KAIROS SOLUÇÕES EM TRANSPORTES,SAO JOSE DOS CAMPOS,2024,"Álcool etílico não desnaturado, com teor alcoó...","1.263.254,00",Litro,Rodoviário,Tanques,Sim,SAO PAULO,SAO PAULO,Ativa
8,06.043.650/0001-09,J.B. TRANSPORTES E SERVIÇOS DE JAGUARIUNA LTDA,JAGUARIUNA,2024,Cloreto de hidrogênio (ácido clorídrico),"7,00",kilogramas,Rodoviário,Armazém Coberto,Não,SAO PAULO,SAO PAULO,Ativa

In [ ]:
# Contar a aparição de cada produto na coluna 'Produto' do DataFrame filtrado
contagem_produtos_filtrados = df_filtered_perigosos['Produto'].value_counts()

print("Top 10 Produtos mais frequentes no DataFrame filtrado por produtos perigosos:")
display(contagem_produtos_filtrados.head(10))

print(f"Número total de produtos únicos no DataFrame filtrado: {len(contagem_produtos_filtrados)}")

Top 10 Produtos mais frequentes no DataFrame filtrado por produtos perigosos:

Produto
Álcool etílico não desnaturado, com teor alcoólico em volume maior ou igual a 80%, anidro ou hidratado para fins carburantes    80446
Produtos químicos, n.e.                                                                                                         79269
Óleo diesel                                                                                                                     61693
Inseticidas para uso na agricultura                                                                                             48674
Herbicidas para uso na agricultura                                                                                              42988
Hidróxido de sódio (soda cáustica)                                                                                              39797
Fungicidas para uso na agricultura                                                                                              29072
Gás liqüefeito de petróleo (GLP)                                                                                                28918
Ácido sulfúrico                                                                                                                 26598
Gasolina automotiva ou para outros usos, exceto para aviação                                                                    21307
Name: count, dtype: int64

Número total de produtos únicos no DataFrame filtrado: 1982

### Salvando o DataFrame Filtrado

In [ ]:
# Definir o nome do novo arquivo CSV
nome_arquivo_saida = 'Dados Tratados - Filtrado.csv'

# Construir o caminho completo para o arquivo de saída
caminho_arquivo_saida = caminho + nome_arquivo_saida

# Salvar o DataFrame df_filtered_perigosos em CSV
df_filtered_perigosos.to_csv(caminho_arquivo_saida, index=False)

print(f"DataFrame filtrado salvo com sucesso em: {caminho_arquivo_saida}")

DataFrame filtrado salvo com sucesso em: /content/drive/My Drive/API 2026 - Cargas perigosas/Dados Tratados - Filtrado.csv

In [ ]:
df_filtered = df[df['Produto'].isin(unique_produtos)]

print(f"Número original de linhas: {len(df)}")
print(f"Número de linhas após o filtro: {len(df_filtered)}")

display(df_filtered.head())

Número original de linhas: 1333721
Número de linhas após o filtro: 1333721

,CNPJ,Razão Social,Município,Ano,Produto,Quantidade Transportada,Unidade de Medida,Tipo de Transporte,Tipo de Armazenamento,Plano de Emergência,UF - origem,UF - destino,Situação Cadastral
0,22.611.457/0001-75,EXPRESSO IGUANA TRANSPORTES LTDA,SAO BERNARDO DO CAMPO,2024,Aspartame,"75,00",kilogramas,Rodoviário,Outros,Sim,SAO PAULO,SAO PAULO,Ativa
1,97.471.676/0001-03,DISTRIBUIDORA DE COMBUSTÍVEIS SAARA LTDA.,CASCAVEL,2024,"Álcool etílico não desnaturado, com teor alcoó...","1.000.000,00",Litro,Rodoviário,Tanques,Sim,SAO PAULO,PARANA,Ativa
2,07.170.894/0001-07,ATOCLEAN AMBIENTAL LTDA,VOTUPORANGA,2024,"Seringas, agulhas, catéteres, cânulas, lanceta...","2.500,00",kilogramas,Rodoviário,Armazém Coberto,Não,SAO PAULO,SAO PAULO,Ativa
3,23.338.864/0001-13,ROGER AUGUSTO SCHWALD TRANSPORTES,SALTO,2024,Tintas e vernizes não especificados para usos ...,"3,00",Unidade,Rodoviário,Outros,Sim,SAO PAULO,SAO PAULO,Ativa
4,23.338.864/0001-13,ROGER AUGUSTO SCHWALD TRANSPORTES,SALTO,2024,Tintas e vernizes não especificados para usos ...,"14,00",Unidade,Rodoviário,Outros,Sim,SAO PAULO,SAO PAULO,Ativa